In [1]:
import pandas as pd
from glob import glob

single_file = pd.read_csv('../../data/raw/MetaMotion/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv')

In [2]:
single_file = pd.read_csv('../../data/raw/MetaMotion/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv')

In [3]:
single_file = pd.read_csv('../../data/raw/MetaMotion/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv')

In [4]:
single_file = pd.read_csv('../../data/raw/MetaMotion/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv')

In [5]:
print(single_file)

        epoch (ms)             time (01:00)  elapsed (s)  x-axis (g)  \
0    1547219408431  2019-01-11T16:10:08.431         0.00       0.010
1    1547219408511  2019-01-11T16:10:08.511         0.08       0.000
2    1547219408591  2019-01-11T16:10:08.591         0.16       0.001
3    1547219408671  2019-01-11T16:10:08.671         0.24      -0.012
4    1547219408751  2019-01-11T16:10:08.751         0.32      -0.013
..             ...                      ...          ...         ...
201  1547219424511  2019-01-11T16:10:24.511        16.08       0.027
202  1547219424591  2019-01-11T16:10:24.591        16.16       0.010
203  1547219424671  2019-01-11T16:10:24.671        16.24       0.011
204  1547219424751  2019-01-11T16:10:24.751        16.32       0.008
205  1547219424831  2019-01-11T16:10:24.831        16.40       0.021

     y-axis (g)  z-axis (g)
0         0.964      -0.087
1         0.961      -0.069
2         0.974      -0.087
3         0.971      -0.084
4         0.954      -0.094
..          ...         ...
201       0.970      -0.091
202       0.990      -0.068
203       0.978      -0.091
204       0.937      -0.085
205       0.966      -0.108

[206 rows x 6 columns]

In [6]:
single_file_gyr = pd.read_csv('../../data/raw/MetaMotion/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv')

In [7]:
single_file_gyr = pd.read_csv('../../data/raw/MetaMotion/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv')

In [8]:
single_file_gyr = pd.read_csv('../../data/raw/MetaMotion/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv')

In [9]:
print(single_file_gyr)

        epoch (ms)             time (01:00)  elapsed (s)  x-axis (deg/s)  \
0    1547219408351  2019-01-11T16:10:08.351         0.00           0.122
1    1547219408391  2019-01-11T16:10:08.391         0.04           2.195
2    1547219408431  2019-01-11T16:10:08.431         0.08           2.622
3    1547219408471  2019-01-11T16:10:08.471         0.12           1.951
4    1547219408511  2019-01-11T16:10:08.511         0.16           1.524
..             ...                      ...          ...             ...
409  1547219424711  2019-01-11T16:10:24.711        16.36           2.195
410  1547219424751  2019-01-11T16:10:24.751        16.40           4.451
411  1547219424791  2019-01-11T16:10:24.791        16.44           7.195
412  1547219424831  2019-01-11T16:10:24.831        16.48           8.963
413  1547219424871  2019-01-11T16:10:24.871        16.52          -3.476

     y-axis (deg/s)  z-axis (deg/s)
0            -5.488          -3.841
1            -9.695          -0.610
2            -8.110          -4.024
3            -4.695          -4.634
4            -2.561          -2.500
..              ...             ...
409          -1.402           4.268
410          -1.220           0.244
411          -4.329           6.524
412          -1.037          -0.366
413           2.134          -5.305

[414 rows x 6 columns]

In [10]:
files = glob("../../data/raw/MetaMotion/MetaMotion/*csv")

In [11]:
len(files)

187

In [12]:
files[0]

'../../data/raw/MetaMotion/MetaMotion/C-dead-medium_MetaWear_2019-01-15T20.28.15.269_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv'

In [13]:
f = files[0]

In [14]:
f = files[0]

In [15]:
f

'../../data/raw/MetaMotion/MetaMotion/C-dead-medium_MetaWear_2019-01-15T20.28.15.269_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv'

In [17]:
data_path = "../../data/raw/MetaMotion/MetaMotion/"

In [18]:
f = files[0]

In [19]:
f.split("-")[0].replace(data_path, "")

'C'

In [20]:
label = f.split("-")[1]

In [21]:
category = f.split("-")[2].rstrip("2")

In [22]:
category

'medium_MetaWear_2019'

In [23]:
category = f.split("-")[2]

In [24]:
category

'medium_MetaWear_2019'

In [25]:
category = f.split("-")[2].rstrip("2")

In [26]:
category = f.split("-")[2].rstrip("123")

In [27]:
df = pd.read_csv(f)

In [28]:
df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g)
0,1547580495831,2019-01-15T20:28:15.831,0.00,0.036,-1.000,-0.270
1,1547580495911,2019-01-15T20:28:15.911,0.08,0.003,-0.979,-0.267
2,1547580495991,2019-01-15T20:28:15.991,0.16,0.046,-1.008,-0.276
3,1547580496071,2019-01-15T20:28:16.071,0.24,0.105,-1.063,-0.232
4,1547580496151,2019-01-15T20:28:16.151,0.32,0.012,-1.041,-0.276
...,...,...,...,...,...,...
405,1547580528231,2019-01-15T20:28:48.231,32.40,-0.087,-1.577,-0.278
406,1547580528311,2019-01-15T20:28:48.311,32.48,0.179,-1.036,0.105
407,1547580528391,2019-01-15T20:28:48.391,32.56,-0.068,-0.953,-0.274
408,1547580528471,2019-01-15T20:28:48.471,32.64,-0.066,-1.063,-0.221
409,1547580528551,2019-01-15T20:28:48.551,32.72,-0.077,-0.998,-0.218

In [30]:
participant = f.split("-")[0].replace(data_path, "")

In [31]:
df["participant"] = participant

In [32]:
label = f.split("-")[1]

In [33]:
df["label"] = label

In [34]:
category = f.split("-")[2].rstrip("123")

In [35]:
df["category"] = category

In [36]:
df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category
0,1547580495831,2019-01-15T20:28:15.831,0.00,0.036,-1.000,-0.270,C,dead,medium_MetaWear_2019
1,1547580495911,2019-01-15T20:28:15.911,0.08,0.003,-0.979,-0.267,C,dead,medium_MetaWear_2019
2,1547580495991,2019-01-15T20:28:15.991,0.16,0.046,-1.008,-0.276,C,dead,medium_MetaWear_2019
3,1547580496071,2019-01-15T20:28:16.071,0.24,0.105,-1.063,-0.232,C,dead,medium_MetaWear_2019
4,1547580496151,2019-01-15T20:28:16.151,0.32,0.012,-1.041,-0.276,C,dead,medium_MetaWear_2019
...,...,...,...,...,...,...,...,...,...
405,1547580528231,2019-01-15T20:28:48.231,32.40,-0.087,-1.577,-0.278,C,dead,medium_MetaWear_2019
406,1547580528311,2019-01-15T20:28:48.311,32.48,0.179,-1.036,0.105,C,dead,medium_MetaWear_2019
407,1547580528391,2019-01-15T20:28:48.391,32.56,-0.068,-0.953,-0.274,C,dead,medium_MetaWear_2019
408,1547580528471,2019-01-15T20:28:48.471,32.64,-0.066,-1.063,-0.221,C,dead,medium_MetaWear_2019
409,1547580528551,2019-01-15T20:28:48.551,32.72,-0.077,-0.998,-0.218,C,dead,medium_MetaWear_2019

In [37]:
category = f.split("-")[2].rstrip("123").rstrip("_Metawear_2019")

In [38]:
category

'medium_MetaW'

In [39]:
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

In [40]:
category

'medium'

In [41]:
accl_df = pd.DataFrame()

In [42]:
gyr_df = pd.DataFrame()

In [44]:
participant = f.split("-")[0].replace(data_path, "")

In [45]:
label = f.split("-")[1]

In [46]:
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

In [47]:
print(category)

medium

In [48]:
for f in files:
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

In [49]:
for f in files:
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")
    print(category)

medium
medium
medium
medium
heavy
heavy
sitting
medium
heavy
medium
medium
medium
medium
medium
medium
heavy
heavy
medium
medium
heavy
sitting
heavy
medium
heavy
heavy
heavy
sitting
medium
heavy
heavy
medium
medium
medium
heavy
medium
heavy
medium
heavy
heavy
heavy
medium
medium
heavy
standing
medium
medium
heavy
medium
heavy
heavy
standing
heavy
heavy
heavy
medium
heavy
heavy
sitting
standing
sitting
heavy
heavy
heavy
medium
heavy
heavy
heavy
medium
medium
medium
heavy
heavy
sitting
heavy
medium
heavy
medium
medium
medium
heavy
heavy
heavy
heavy
medium
medium
medium
heavy
heavy
standing
heavy
medium
heavy
heavy
medium
medium
sitting
heavy
heavy
heavy
medium
medium
heavy
medium
medium
heavy
heavy
heavy
medium
medium
medium
medium
heavy
heavy
sitting
heavy
medium
heavy
heavy
medium
heavy
medium
heavy
medium
heavy
medium
medium
heavy
medium
medium
medium
medium
heavy
medium
heavy
medium
medium
heavy
medium
medium
heavy
heavy
heavy
heavy
heavy
standing
heavy
medium
medium
heavy
heavy
heavy
standing
medium
medium
standing
medium
medium
heavy
heavy
medium
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
heavy
standing
medium
medium
heavy
heavy
medium
heavy
heavy
heavy
heavy
heavy
heavy
heavy
medium
heavy
medium
heavy
heavy

In [50]:
if "Accelerometer" in f:
    acc_d = pd.concate([accl_df, df])

In [51]:
if "Gyroscope" in f:
    gyr_df - pd.concat([gyr_df, df])

In [52]:
gyr_df

Empty DataFrame
Columns: []
Index: []

In [53]:
accl_df

Empty DataFrame
Columns: []
Index: []

In [54]:
len(accl_df)

0

In [56]:
for f in files:
    # extract the features
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")
    # read into dataframe
    df = pd.read_csv(f)
    # add columns to the dataframe
    df["participant"] = participant
    df["label"] = label
    df["category"] = category
    if "Accelerometer" in f:
        acc_d = pd.concat([accl_df, df])
    if "Gyroscope" in f:
        gyr_df - pd.concat([gyr_df, df])

In [57]:
len(accl_df)

0

In [58]:
accl_df

Empty DataFrame
Columns: []
Index: []

In [59]:
for f in files:
    # extract the features
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")
    # read into dataframe
    df = pd.read_csv(f)
    # add columns to the dataframe
    df["participant"] = participant
    df["label"] = label
    df["category"] = category
    if "Accelerometer" in f:
        accl_df = pd.concat([accl_df, df])
    if "Gyroscope" in f:
        gyr_df - pd.concat([gyr_df, df])

In [60]:
len(accl_df)

23578

In [62]:
gyr_df

Empty DataFrame
Columns: []
Index: []

In [63]:
len(gyr_df)

0

In [64]:
accl_df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category
0,1547580495831,2019-01-15T20:28:15.831,0.00,0.036,-1.000,-0.270,C,dead,medium
1,1547580495911,2019-01-15T20:28:15.911,0.08,0.003,-0.979,-0.267,C,dead,medium
2,1547580495991,2019-01-15T20:28:15.991,0.16,0.046,-1.008,-0.276,C,dead,medium
3,1547580496071,2019-01-15T20:28:16.071,0.24,0.105,-1.063,-0.232,C,dead,medium
4,1547580496151,2019-01-15T20:28:16.151,0.32,0.012,-1.041,-0.276,C,dead,medium
...,...,...,...,...,...,...,...,...,...
215,1547221225621,2019-01-11T16:40:25.621,17.20,-0.173,1.061,-0.206,B,ohp,heavy
216,1547221225701,2019-01-11T16:40:25.701,17.28,-0.164,1.123,-0.254,B,ohp,heavy
217,1547221225781,2019-01-11T16:40:25.781,17.36,-0.034,1.019,-0.192,B,ohp,heavy
218,1547221225861,2019-01-11T16:40:25.861,17.44,-0.095,0.942,0.015,B,ohp,heavy
219,1547221225941,2019-01-11T16:40:25.941,17.52,-0.078,1.013,-0.114,B,ohp,heavy

In [65]:
gyr_df = pd.DataFrame()

In [66]:
for f in files:
    # extract the features
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")
    # read into dataframe
    df = pd.read_csv(f)
    # add columns to the dataframe
    df["participant"] = participant
    df["label"] = label
    df["category"] = category
    if "Accelerometer" in f:
        accl_df = pd.concat([accl_df, df])
    if "Gyroscope" in f:
        gyr_df - pd.concat([gyr_df, df])

len(gyr_df)

0

In [67]:
accl_set = 1

In [68]:
gyr_set = 1

In [69]:
for f in files:
    # extract the features
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")
    # read into dataframe
    df = pd.read_csv(f)
    # add columns to the dataframe
    df["participant"] = participant
    df["label"] = label
    df["category"] = category
    if "Accelerometer" in f:
        accl_df = pd.concat([accl_df, df])
    if "Gyroscope" in f:
        gyr_df - pd.concat([gyr_df, df])

len(gyr_df)

0

In [70]:
gyr_df = pd.concat([gyr_df, df])

In [71]:
for f in files:
    # extract the features
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")
    # read into dataframe
    df = pd.read_csv(f)
    # add columns to the dataframe
    df["participant"] = participant
    df["label"] = label
    df["category"] = category
    if "Accelerometer" in f:
        accl_df = pd.concat([accl_df, df])
    if "Gyroscope" in f:
        gyr_df = pd.concat([gyr_df, df])

len(gyr_df)

47436

In [73]:
gyr_df = pd.concat([gyr_df, df])

In [74]:
for f in files:
    # extract the features
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")
    # read into dataframe
    df = pd.read_csv(f)
    # add columns to the dataframe
    df["participant"] = participant
    df["label"] = label
    df["category"] = category
    if "Accelerometer" in f:
        df["set"] = accl_set
        accl_df = pd.concat([accl_df, df])
    if "Gyroscope" in f:
        df["set"] = gyr_set
        gyr_df = pd.concat([gyr_df, df])

In [75]:
f

'../../data/raw/MetaMotion/MetaMotion/A-row-heavy_MetaWear_2019-01-14T15.04.06.123_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv'

In [76]:
gyr_df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
0,1547474646331,2019-01-14T15:04:06.331,0.00,1.402,-6.280,1.585,A,row,heavy,NaN
1,1547474646371,2019-01-14T15:04:06.371,0.04,1.341,-5.427,0.915,A,row,heavy,NaN
2,1547474646411,2019-01-14T15:04:06.411,0.08,-1.280,0.671,-1.829,A,row,heavy,NaN
3,1547474646451,2019-01-14T15:04:06.451,0.12,-1.829,0.366,-0.549,A,row,heavy,NaN
4,1547474646491,2019-01-14T15:04:06.491,0.16,-1.951,-2.683,1.829,A,row,heavy,NaN
...,...,...,...,...,...,...,...,...,...,...
213,1547474654851,2019-01-14T15:04:14.851,8.52,2.317,-1.524,-2.378,A,row,heavy,1.0
214,1547474654891,2019-01-14T15:04:14.891,8.56,2.622,-7.561,2.073,A,row,heavy,1.0
215,1547474654931,2019-01-14T15:04:14.931,8.60,0.305,-2.744,2.500,A,row,heavy,1.0
216,1547474654971,2019-01-14T15:04:14.971,8.64,-0.671,-3.293,-0.061,A,row,heavy,1.0
217,1547474655011,2019-01-14T15:04:15.011,8.68,-0.610,-0.427,1.159,A,row,heavy,1.0

In [77]:
accl_df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
0,1547580495831,2019-01-15T20:28:15.831,0.00,0.036,-1.000,-0.270,C,dead,medium,NaN
1,1547580495911,2019-01-15T20:28:15.911,0.08,0.003,-0.979,-0.267,C,dead,medium,NaN
2,1547580495991,2019-01-15T20:28:15.991,0.16,0.046,-1.008,-0.276,C,dead,medium,NaN
3,1547580496071,2019-01-15T20:28:16.071,0.24,0.105,-1.063,-0.232,C,dead,medium,NaN
4,1547580496151,2019-01-15T20:28:16.151,0.32,0.012,-1.041,-0.276,C,dead,medium,NaN
...,...,...,...,...,...,...,...,...,...,...
215,1547221225621,2019-01-11T16:40:25.621,17.20,-0.173,1.061,-0.206,B,ohp,heavy,1.0
216,1547221225701,2019-01-11T16:40:25.701,17.28,-0.164,1.123,-0.254,B,ohp,heavy,1.0
217,1547221225781,2019-01-11T16:40:25.781,17.36,-0.034,1.019,-0.192,B,ohp,heavy,1.0
218,1547221225861,2019-01-11T16:40:25.861,17.44,-0.095,0.942,0.015,B,ohp,heavy,1.0
219,1547221225941,2019-01-11T16:40:25.941,17.52,-0.078,1.013,-0.114,B,ohp,heavy,1.0

In [78]:
for f in files:
    # extract the features
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")
    # read into dataframe
    df = pd.read_csv(f)
    # add columns to the dataframe
    df["participant"] = participant
    df["label"] = label
    df["category"] = category
    if "Accelerometer" in f:
        df["set"] = accl_set # remove NaN for set values
        accl_set += 1
        accl_df = pd.concat([accl_df, df])
    if "Gyroscope" in f:
        df["set"] = gyr_set # remove NaN for set values
        gyr_set += 1
        gyr_df = pd.concat([gyr_df, df])

In [79]:
accl_df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
0,1547580495831,2019-01-15T20:28:15.831,0.00,0.036,-1.000,-0.270,C,dead,medium,NaN
1,1547580495911,2019-01-15T20:28:15.911,0.08,0.003,-0.979,-0.267,C,dead,medium,NaN
2,1547580495991,2019-01-15T20:28:15.991,0.16,0.046,-1.008,-0.276,C,dead,medium,NaN
3,1547580496071,2019-01-15T20:28:16.071,0.24,0.105,-1.063,-0.232,C,dead,medium,NaN
4,1547580496151,2019-01-15T20:28:16.151,0.32,0.012,-1.041,-0.276,C,dead,medium,NaN
...,...,...,...,...,...,...,...,...,...,...
215,1547221225621,2019-01-11T16:40:25.621,17.20,-0.173,1.061,-0.206,B,ohp,heavy,94.0
216,1547221225701,2019-01-11T16:40:25.701,17.28,-0.164,1.123,-0.254,B,ohp,heavy,94.0
217,1547221225781,2019-01-11T16:40:25.781,17.36,-0.034,1.019,-0.192,B,ohp,heavy,94.0
218,1547221225861,2019-01-11T16:40:25.861,17.44,-0.095,0.942,0.015,B,ohp,heavy,94.0
219,1547221225941,2019-01-11T16:40:25.941,17.52,-0.078,1.013,-0.114,B,ohp,heavy,94.0

In [80]:
data_path = "../../data/raw/MetaMotion/MetaMotion/"

In [81]:
f = files[0]

In [82]:
participant = f.split("-")[0].replace(data_path, "")

In [83]:
label = f.split("-")[1]

In [84]:
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

In [85]:
df = pd.read_csv(f)

In [86]:
df["participant"] = participant

In [87]:
df["label"] = label

In [88]:
df["category"] = category

In [89]:
accl_df = pd.DataFrame()

In [90]:
gyr_df = pd.DataFrame()

In [91]:
accl_set = 1

In [92]:
gyr_set = 1

In [93]:
for f in files:
    # extract the features
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")
    # read into dataframe
    df = pd.read_csv(f)
    # add columns to the dataframe
    df["participant"] = participant
    df["label"] = label
    df["category"] = category
    if "Accelerometer" in f:
        df["set"] = accl_set # remove NaN for set values
        accl_set += 1
        accl_df = pd.concat([accl_df, df])
    if "Gyroscope" in f:
        df["set"] = gyr_set # remove NaN for set values
        gyr_set += 1
        gyr_df = pd.concat([gyr_df, df])

In [94]:
len(gyr_df)

47218

In [95]:
gyr_df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
0,1547667034809,2019-01-16 20:30:34.809,0.00,4.207,-2.012,-0.305,E,dead,medium,1
1,1547667034849,2019-01-16 20:30:34.849,0.04,3.659,-2.317,0.305,E,dead,medium,1
2,1547667034889,2019-01-16 20:30:34.889,0.08,3.415,-1.890,1.341,E,dead,medium,1
3,1547667034929,2019-01-16 20:30:34.929,0.12,5.488,-3.415,2.988,E,dead,medium,1
4,1547667034969,2019-01-16 20:30:34.969,0.16,7.012,-7.927,3.049,E,dead,medium,1
...,...,...,...,...,...,...,...,...,...,...
213,1547474654851,2019-01-14T15:04:14.851,8.52,2.317,-1.524,-2.378,A,row,heavy,93
214,1547474654891,2019-01-14T15:04:14.891,8.56,2.622,-7.561,2.073,A,row,heavy,93
215,1547474654931,2019-01-14T15:04:14.931,8.60,0.305,-2.744,2.500,A,row,heavy,93
216,1547474654971,2019-01-14T15:04:14.971,8.64,-0.671,-3.293,-0.061,A,row,heavy,93
217,1547474655011,2019-01-14T15:04:15.011,8.68,-0.610,-0.427,1.159,A,row,heavy,93

In [96]:
pd.to_datetime(accl_df["epoch (ms)"], unit="ms")

0     2019-01-15 19:28:15.831
1     2019-01-15 19:28:15.911
2     2019-01-15 19:28:15.991
3     2019-01-15 19:28:16.071
4     2019-01-15 19:28:16.151
                ...
215   2019-01-11 15:40:25.621
216   2019-01-11 15:40:25.701
217   2019-01-11 15:40:25.781
218   2019-01-11 15:40:25.861
219   2019-01-11 15:40:25.941
Name: epoch (ms), Length: 23578, dtype: datetime64[ns]

In [97]:
accl_df.index = pd.to_datetime(accl_df["epoch (ms)"], unit="ms")

In [98]:
gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")

In [99]:
del accl_df["epoch (ms)"]
del accl_df["time (01:00)"]
del accl_df["elapsed (s)"]
del gyr_df["epoch (ms)"]
del gyr_df["time (01:00)"]
del gyr_df["elapsed (s)"]

In [100]:
accl_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-15 19:28:15.831,0.036,-1.000,-0.270,C,dead,medium,1
2019-01-15 19:28:15.911,0.003,-0.979,-0.267,C,dead,medium,1
2019-01-15 19:28:15.991,0.046,-1.008,-0.276,C,dead,medium,1
2019-01-15 19:28:16.071,0.105,-1.063,-0.232,C,dead,medium,1
2019-01-15 19:28:16.151,0.012,-1.041,-0.276,C,dead,medium,1
...,...,...,...,...,...,...,...
2019-01-11 15:40:25.621,-0.173,1.061,-0.206,B,ohp,heavy,94
2019-01-11 15:40:25.701,-0.164,1.123,-0.254,B,ohp,heavy,94
2019-01-11 15:40:25.781,-0.034,1.019,-0.192,B,ohp,heavy,94
2019-01-11 15:40:25.861,-0.095,0.942,0.015,B,ohp,heavy,94
2019-01-11 15:40:25.941,-0.078,1.013,-0.114,B,ohp,heavy,94

In [101]:
def read_data_from_files(files):
    # read all files
    accl_df = pd.DataFrame()
    gyr_df = pd.DataFrame()
    # to create unique identifier
    accl_set = 1
    gyr_set = 1
    for f in files:
        # extract the features
        participant = f.split("-")[0].replace(data_path, "")
        label = f.split("-")[1]
        category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")
        # read into dataframe
        df = pd.read_csv(f)
        # add columns to the dataframe
        df["participant"] = participant
        df["label"] = label
        df["category"] = category
        if "Accelerometer" in f:
            df["set"] = accl_set # remove NaN for set values
            accl_set += 1
            accl_df = pd.concat([accl_df, df])
        if "Gyroscope" in f:
            df["set"] = gyr_set # remove NaN for set values
            gyr_set += 1
            gyr_df = pd.concat([gyr_df, df])
    accl_df.index = pd.to_datetime(accl_df["epoch (ms)"], unit="ms")
    gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit="ms")
    # remove column
    del accl_df["epoch (ms)"]
    del accl_df["time (01:00)"]
    del accl_df["elapsed (s)"]
    del gyr_df["epoch (ms)"]
    del gyr_df["time (01:00)"]
    del gyr_df["elapsed (s)"]        
    return accl_df, gyr_df

In [102]:
accl_df, gyr_df = read_data_from_files(files)

In [103]:
accl_df, gyr_df = read_data_from_files(files)

In [104]:
gyr_df

,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,
2019-01-16 19:30:34.809,4.207,-2.012,-0.305,E,dead,medium,1
2019-01-16 19:30:34.849,3.659,-2.317,0.305,E,dead,medium,1
2019-01-16 19:30:34.889,3.415,-1.890,1.341,E,dead,medium,1
2019-01-16 19:30:34.929,5.488,-3.415,2.988,E,dead,medium,1
2019-01-16 19:30:34.969,7.012,-7.927,3.049,E,dead,medium,1
...,...,...,...,...,...,...,...
2019-01-14 14:04:14.851,2.317,-1.524,-2.378,A,row,heavy,93
2019-01-14 14:04:14.891,2.622,-7.561,2.073,A,row,heavy,93
2019-01-14 14:04:14.931,0.305,-2.744,2.500,A,row,heavy,93
2019-01-14 14:04:14.971,-0.671,-3.293,-0.061,A,row,heavy,93
2019-01-14 14:04:15.011,-0.610,-0.427,1.159,A,row,heavy,93

In [105]:
accl_d

NameError: name 'accl_d' is not defined

In [106]:
accl_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-15 19:28:15.831,0.036,-1.000,-0.270,C,dead,medium,1
2019-01-15 19:28:15.911,0.003,-0.979,-0.267,C,dead,medium,1
2019-01-15 19:28:15.991,0.046,-1.008,-0.276,C,dead,medium,1
2019-01-15 19:28:16.071,0.105,-1.063,-0.232,C,dead,medium,1
2019-01-15 19:28:16.151,0.012,-1.041,-0.276,C,dead,medium,1
...,...,...,...,...,...,...,...
2019-01-11 15:40:25.621,-0.173,1.061,-0.206,B,ohp,heavy,94
2019-01-11 15:40:25.701,-0.164,1.123,-0.254,B,ohp,heavy,94
2019-01-11 15:40:25.781,-0.034,1.019,-0.192,B,ohp,heavy,94
2019-01-11 15:40:25.861,-0.095,0.942,0.015,B,ohp,heavy,94
2019-01-11 15:40:25.941,-0.078,1.013,-0.114,B,ohp,heavy,94

In [107]:
pd.concat([accl_df.iloc[:,:3], gyr_df], axis=1)

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,80.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,80.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,80.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,80.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,80.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [108]:
pd.concat([accl_df.iloc[:,:3], gyr_df], axis=1)

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,80.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,80.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,80.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,80.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,80.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [109]:
pd.concat([accl_df.iloc[:3], gyr_df], axis=1)

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,80.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,80.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,80.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,80.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:33:27.647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.537,-5.061,2.683,E,row,medium,92.0
2019-01-20 17:33:27.687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.305,-1.829,1.402,E,row,medium,92.0
2019-01-20 17:33:27.727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.488,3.659,-2.195,E,row,medium,92.0
2019-01-20 17:33:27.767,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.915,-0.427,1.159,E,row,medium,92.0
2019-01-20 17:33:27.807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.098,-4.024,0.976,E,row,medium,92.0

In [110]:
accl_df, gyr_df = read_data_from_files(files)

In [111]:
accl_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-15 19:28:15.831,0.036,-1.000,-0.270,C,dead,medium,1
2019-01-15 19:28:15.911,0.003,-0.979,-0.267,C,dead,medium,1
2019-01-15 19:28:15.991,0.046,-1.008,-0.276,C,dead,medium,1
2019-01-15 19:28:16.071,0.105,-1.063,-0.232,C,dead,medium,1
2019-01-15 19:28:16.151,0.012,-1.041,-0.276,C,dead,medium,1
...,...,...,...,...,...,...,...
2019-01-11 15:40:25.621,-0.173,1.061,-0.206,B,ohp,heavy,94
2019-01-11 15:40:25.701,-0.164,1.123,-0.254,B,ohp,heavy,94
2019-01-11 15:40:25.781,-0.034,1.019,-0.192,B,ohp,heavy,94
2019-01-11 15:40:25.861,-0.095,0.942,0.015,B,ohp,heavy,94
2019-01-11 15:40:25.941,-0.078,1.013,-0.114,B,ohp,heavy,94

In [112]:
gyr_df

,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,
2019-01-16 19:30:34.809,4.207,-2.012,-0.305,E,dead,medium,1
2019-01-16 19:30:34.849,3.659,-2.317,0.305,E,dead,medium,1
2019-01-16 19:30:34.889,3.415,-1.890,1.341,E,dead,medium,1
2019-01-16 19:30:34.929,5.488,-3.415,2.988,E,dead,medium,1
2019-01-16 19:30:34.969,7.012,-7.927,3.049,E,dead,medium,1
...,...,...,...,...,...,...,...
2019-01-14 14:04:14.851,2.317,-1.524,-2.378,A,row,heavy,93
2019-01-14 14:04:14.891,2.622,-7.561,2.073,A,row,heavy,93
2019-01-14 14:04:14.931,0.305,-2.744,2.500,A,row,heavy,93
2019-01-14 14:04:14.971,-0.671,-3.293,-0.061,A,row,heavy,93
2019-01-14 14:04:15.011,-0.610,-0.427,1.159,A,row,heavy,93

In [113]:
pd.concat([accl_df.iloc[:,:3], gyr_df], axis=1)

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,80.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,80.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,80.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,80.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,80.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [115]:
merged_data = pd.concat([accl_df.iloc[:,:3], gyr_df], axis=1)

In [116]:
merged_data.dropna()

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,2.622,-8.110,-4.024,A,bench,heavy,47.0
2019-01-11 15:10:08.511,0.000,0.961,-0.069,1.524,-2.561,-2.500,A,bench,heavy,47.0
2019-01-11 15:10:08.591,0.001,0.974,-0.087,1.707,-5.366,0.915,A,bench,heavy,47.0
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,2.683,-4.146,-1.220,A,bench,heavy,47.0
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,1.524,0.610,-3.171,A,bench,heavy,47.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-15 19:04:25.561,0.369,0.591,0.761,11.220,-5.061,-5.061,A,squat,heavy,56.0
2019-01-15 19:04:25.641,0.387,0.566,0.776,3.963,-2.988,-0.793,A,squat,heavy,56.0
2019-01-15 19:04:25.721,0.361,0.574,0.680,15.305,-3.293,-0.671,A,squat,heavy,56.0
2019-01-15 19:04:25.801,0.353,0.583,0.635,30.366,-0.122,-4.573,A,squat,heavy,56.0
2019-01-15 19:04:25.881,0.359,0.605,0.678,14.756,-6.585,-2.378,A,squat,heavy,56.0

In [117]:
"set"

'set'

In [121]:
merged_data.columns = ["accl_x", "accl_y", "accl_z", "gyr_x", "gyr_y", "gyr_z", "label", "category", "participant", "set",]

In [122]:
merged_data.columns

Index(['accl_x', 'accl_y', 'accl_z', 'gyr_x', 'gyr_y', 'gyr_z', 'label',
       'category', 'participant', 'set'],
      dtype='object')

In [123]:
merged_data.columns

Index(['accl_x', 'accl_y', 'accl_z', 'gyr_x', 'gyr_y', 'gyr_z', 'label',
       'category', 'participant', 'set'],
      dtype='object')

In [124]:
merged_data

,accl_x,accl_y,accl_z,gyr_x,gyr_y,gyr_z,label,category,participant,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,80.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,80.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,80.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,80.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,80.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
sampling = {"accl_x": "mean", "accl_y":"mean", "accl_z":"mean", "gyr_x":"mean", "gyr_y":"mean", "gyr_z":"mean", "label":"mean", "category":"last", "participant":"last", "set":"last",}

In [126]:
merged_data[:1000].resample(rule="200ms").apply(sampling)

TypeError: Could not convert BB to numeric

In [127]:
sampling = {"accl_x": "mean", "accl_y":"mean", "accl_z":"mean", "gyr_x":"mean", "gyr_y":"mean", "gyr_z":"mean", "label":"last", "category":"last", "participant":"last", "set":"last",}

In [128]:
merged_data[:1000].resample(rule="200ms").apply(sampling)

,accl_x,accl_y,accl_z,gyr_x,gyr_y,gyr_z,label,category,participant,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.800,NaN,NaN,NaN,-9.69550,-1.7985,4.5735,B,bench,heavy,80.0
2019-01-11 15:08:05.000,NaN,NaN,NaN,-2.01220,-0.4270,-1.6218,B,bench,heavy,80.0
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.89040,2.4392,0.9388,B,bench,heavy,80.0
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.68260,-0.8904,2.1708,B,bench,heavy,80.0
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.56080,-0.2560,-1.4146,B,bench,heavy,80.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-11 15:10:21.600,-0.174000,1.092667,-0.153333,-4.96360,-16.4026,21.9026,A,bench,heavy,47.0
2019-01-11 15:10:21.800,-0.219500,1.402500,-0.109000,-7.52440,18.6706,-22.6828,A,bench,heavy,47.0
2019-01-11 15:10:22.000,-0.192000,0.871667,-0.155667,2.60980,8.7070,-14.8658,A,bench,heavy,47.0
2019-01-11 15:10:22.200,-0.227000,0.891000,-0.170000,5.39020,4.0000,-0.3780,A,bench,heavy,47.0
2019-01-11 15:10:22.400,-0.225500,0.919500,-0.205500,6.34125,0.5795,9.9085,A,bench,heavy,47.0